server:
  port: 8001
  servlet:
    context-path: /register

spring:
  application:
    name: DASH-Register

  boot:
    admin:
      client:
        url: http://localhost:8401

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 30
    serviceUrl:
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/

